In [7]:
import pandas as pd

df = pd.read_csv("../data/nba_player_stats_2025_26.csv")

In [8]:
import os

os.getcwd()

'/Users/sonicapou/nba-scorer-effiency/notebooks'

In [9]:
os.listdir("../data")

['nba_player_stats_2025_26.csv']

In [10]:
df = pd.read_csv("../data/nba_player_stats_2025_26.csv")

In [11]:
df.head()

   PLAYER_ID    PLAYER_NAME  ... FP_HIGH_SCORE_RANK  TEAM_COUNT
0    1630639    A.J. Lawson  ...                454           1
1    1631260       AJ Green  ...                167           1
2    1642358     AJ Johnson  ...                412           2
3     203932   Aaron Gordon  ...                250           1
4    1628988  Aaron Holiday  ...                352           1

[5 rows x 69 columns]

In [12]:
df.columns.tolist()

['PLAYER_ID',
 'PLAYER_NAME',
 'NICKNAME',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'AGE',
 'GP',
 'W',
 'L',
 'W_PCT',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'TOV',
 'STL',
 'BLK',
 'BLKA',
 'PF',
 'PFD',
 'PTS',
 'PLUS_MINUS',
 'NBA_FANTASY_PTS',
 'DD2',
 'TD3',
 'WNBA_FANTASY_PTS',
 'FP_HIGH_SCORE',
 'GP_RANK',
 'W_RANK',
 'L_RANK',
 'W_PCT_RANK',
 'MIN_RANK',
 'FGM_RANK',
 'FGA_RANK',
 'FG_PCT_RANK',
 'FG3M_RANK',
 'FG3A_RANK',
 'FG3_PCT_RANK',
 'FTM_RANK',
 'FTA_RANK',
 'FT_PCT_RANK',
 'OREB_RANK',
 'DREB_RANK',
 'REB_RANK',
 'AST_RANK',
 'TOV_RANK',
 'STL_RANK',
 'BLK_RANK',
 'BLKA_RANK',
 'PF_RANK',
 'PFD_RANK',
 'PTS_RANK',
 'PLUS_MINUS_RANK',
 'NBA_FANTASY_PTS_RANK',
 'DD2_RANK',
 'TD3_RANK',
 'WNBA_FANTASY_PTS_RANK',
 'FP_HIGH_SCORE_RANK',
 'TEAM_COUNT']

In [13]:
df[df["PLAYER_NAME"] == "Shai Gilgeous-Alexander"][
    ["PLAYER_NAME", "GP", "MIN", "PTS", "FGA", "FTA"]
]

                 PLAYER_NAME  GP          MIN   PTS   FGA  FTA
501  Shai Gilgeous-Alexander  68  2258.946667  2117  1321  614

In [14]:
scoring_df = df[
    [
        "PLAYER_NAME",
        "TEAM_ABBREVIATION",
        "GP",
        "MIN",
        "PTS",
        "FGM",
        "FGA",
        "FG_PCT",
        "FG3M",
        "FG3A",
        "FG3_PCT",
        "FTM",
        "FTA",
        "FT_PCT"
    ]
].copy()

scoring_df.head()

     PLAYER_NAME TEAM_ABBREVIATION  GP          MIN  ...  FG3_PCT  FTM  FTA  FT_PCT
0    A.J. Lawson               TOR  24   226.115000  ...    0.422   14   18   0.778
1       AJ Green               MIL  78  2269.933333  ...    0.419   53   62   0.855
2     AJ Johnson               DAL  48   453.433333  ...    0.211   34   40   0.850
3   Aaron Gordon               DEN  36  1004.958333  ...    0.389  125  163   0.767
4  Aaron Holiday               HOU  57   780.731667  ...    0.394   35   41   0.854

[5 rows x 14 columns]

In [15]:
scoring_df["PTS_PER_GAME"] = scoring_df["PTS"] / scoring_df["GP"]

scoring_df[
    ["PLAYER_NAME", "GP", "PTS", "PTS_PER_GAME"]
].head()

     PLAYER_NAME  GP  PTS  PTS_PER_GAME
0    A.J. Lawson  24  101      4.208333
1       AJ Green  78  809     10.371795
2     AJ Johnson  48  160      3.333333
3   Aaron Gordon  36  582     16.166667
4  Aaron Holiday  57  312      5.473684

In [16]:
scoring_df[["GP", "MIN"]].describe()

               GP          MIN
count  582.000000   582.000000
mean    45.792096  1019.758648
std     24.937300   771.980982
min      1.000000     2.666667
25%     23.000000   293.239583
50%     51.000000   940.295833
75%     67.750000  1609.389167
max     82.000000  2953.150000

In [17]:
(scoring_df["MIN"] >= 500).sum()

np.int64(378)

In [18]:
(scoring_df["MIN"] >= 1000).sum()

np.int64(279)

In [19]:
qualified_df = scoring_df[scoring_df["MIN"] >= 500].copy()

qualified_df.shape

(378, 15)

In [20]:
qualified_df["TS_PCT"] = qualified_df["PTS"] / ( 
    2 * (qualified_df["FGA"] + 0.44 * qualified_df["FTA"])
)

qualified_df[
    ["PLAYER_NAME", "PTS_PER_GAME", "FG_PCT", "TS_PCT"]
].head()

     PLAYER_NAME  PTS_PER_GAME  FG_PCT    TS_PCT
1       AJ Green     10.371795   0.424  0.626860
3   Aaron Gordon     16.166667   0.497  0.619518
4  Aaron Holiday      5.473684   0.417  0.577692
5  Aaron Nesmith     13.800000   0.414  0.553634
6  Aaron Wiggins      9.400000   0.431  0.538155

In [21]:
qualified_df["TS_PCT"].describe()

count    378.000000
mean       0.578910
std        0.052143
min        0.431872
25%        0.544139
50%        0.575659
75%        0.609401
max        0.772290
Name: TS_PCT, dtype: float64

In [22]:
(qualified_df["PTS_PER_GAME"] >= 10).sum()

np.int64(194)

In [23]:
(qualified_df["PTS_PER_GAME"] >= 15).sum()

np.int64(95)

In [24]:
(qualified_df["PTS_PER_GAME"] >= 20).sum()

np.int64(47)

In [25]:
scorers_df = qualified_df[
    qualified_df["PTS_PER_GAME"] >= 15
].copy()

scorers_df.shape

(95, 16)

In [26]:
scorers_df[
    ["PLAYER_NAME", "TEAM_ABBREVIATION", "PTS_PER_GAME", "TS_PCT"]
].sort_values(
    by="TS_PCT",
    ascending=False
).head(10)

                 PLAYER_NAME TEAM_ABBREVIATION  PTS_PER_GAME    TS_PCT
232              Jalen Duren               DET     19.500000  0.687865
429             Nikola Jokić               DEN     27.676923  0.669669
253            Jarrett Allen               CLE     15.357143  0.668907
501  Shai Gilgeous-Alexander               OKC     31.132353  0.665238
186    Giannis Antetokounmpo               MIL     27.583333  0.657546
88             Chet Holmgren               OKC     17.115942  0.653237
275         Jimmy Butler III               GSW     20.000000  0.645951
580          Zion Williamson               NOP     21.000000  0.643535
37             Austin Reaves               LAL     23.274510  0.641455
333             Kevin Durant               HOU     25.974359  0.640539

In [27]:
scorers_df[
    ["PLAYER_NAME", "TEAM_ABBREVIATION", "PTS_PER_GAME", "TS_PCT"]
].sort_values(
    by="PTS_PER_GAME",
    ascending=False
).head(10)

                 PLAYER_NAME TEAM_ABBREVIATION  PTS_PER_GAME    TS_PCT
372              Luka Dončić               LAL     33.484375  0.615522
501  Shai Gilgeous-Alexander               OKC     31.132353  0.665238
31           Anthony Edwards               MIN     28.803279  0.617236
260             Jaylen Brown               BOS     28.704225  0.572845
554             Tyrese Maxey               PHI     28.285714  0.587718
320            Kawhi Leonard               LAC     27.892308  0.629060
154         Donovan Mitchell               CLE     27.885714  0.612988
429             Nikola Jokić               DEN     27.676923  0.669669
186    Giannis Antetokounmpo               MIL     27.583333  0.657546
279              Joel Embiid               PHI     26.868421  0.604571

In [28]:
import plotly.express as px

fig = px.scatter(
    scorers_df,
    x="PTS_PER_GAME",
    y="TS_PCT",
    hover_name="PLAYER_NAME",
    title="Scoring Volume vs. Scoring Efficiency"
)

fig.show()

In [29]:
correlation = scorers_df["PTS_PER_GAME"].corr(
    scorers_df["TS_PCT"]
)

correlation

np.float64(0.3738586634263849)

In [30]:
scorers_df["THREE_POINT_ATTEMPT_RATE"] = (
    scorers_df["FG3A"] / scorers_df["FGA"]
)

scorers_df[
    ["PLAYER_NAME", "FG3A", "FGA", "THREE_POINT_ATTEMPT_RATE"]
].head(10)

        PLAYER_NAME  FG3A   FGA  THREE_POINT_ATTEMPT_RATE
3      Aaron Gordon   157   398                  0.394472
16        Alex Sarr   150   656                  0.228659
19   Alperen Sengun   131  1123                  0.116652
21    Amen Thompson   116  1044                  0.111111
26  Andrew Nembhard   296   753                  0.393094
27   Andrew Wiggins   333   821                  0.405603
30    Anthony Davis    37   334                  0.110778
31  Anthony Edwards   514  1231                  0.417547
37    Austin Reaves   328   762                  0.430446
39      Bam Adebayo   400  1145                  0.349345

In [31]:
scorers_df["FREE_THROW_RATE"] = (
    scorers_df["FTA"] / scorers_df["FGA"]
)

scorers_df[
    ["PLAYER_NAME", "FTA", "FGA", "FREE_THROW_RATE"]
].head(10)

        PLAYER_NAME  FTA   FGA  FREE_THROW_RATE
3      Aaron Gordon  163   398         0.409548
16        Alex Sarr  146   656         0.222561
19   Alperen Sengun  376  1123         0.334817
21    Amen Thompson  390  1044         0.373563
26  Andrew Nembhard  234   753         0.310757
27   Andrew Wiggins  162   821         0.197320
30    Anthony Davis   81   334         0.242515
31  Anthony Edwards  437  1231         0.354996
37    Austin Reaves  371   762         0.486877
39      Bam Adebayo  423  1145         0.369432

In [32]:
three_point_correlation = scorers_df["THREE_POINT_ATTEMPT_RATE"].corr(
    scorers_df["TS_PCT"]
)

free_throw_correlation = scorers_df["FREE_THROW_RATE"].corr(
    scorers_df["TS_PCT"]
)

three_point_correlation, free_throw_correlation

(np.float64(-0.20718252426113695), np.float64(0.553813839239505))

In [33]:
three_point_pct_correlation = scorers_df["FG3_PCT"].corr(
    scorers_df["TS_PCT"]
)

three_point_pct_correlation

np.float64(-0.03597155992985137)

In [34]:
free_throw_pct_correlation = scorers_df["FT_PCT"].corr(
    scorers_df["TS_PCT"]
)

free_throw_pct_correlation

np.float64(0.09828326957691508)

In [35]:
fg_pct_correlation = scorers_df["FG_PCT"].corr(
    scorers_df["TS_PCT"]
)

fg_pct_correlation

np.float64(0.7278022013713988)

In [36]:
scorers_df["FG2_PCT"] = (
    (scorers_df["FGM"] - scorers_df["FG3M"])
    / (scorers_df["FGA"] - scorers_df["FG3A"])
)

scorers_df[
    ["PLAYER_NAME", "FG_PCT", "FG2_PCT", "FG3_PCT", "TS_PCT"]
].head(10)

        PLAYER_NAME  FG_PCT   FG2_PCT  FG3_PCT    TS_PCT
3      Aaron Gordon   0.497  0.568465    0.389  0.619518
16        Alex Sarr   0.482  0.525692    0.333  0.543569
19   Alperen Sengun   0.519  0.547379    0.305  0.568905
21    Amen Thompson   0.534  0.573276    0.216  0.593534
26  Andrew Nembhard   0.442  0.494530    0.361  0.564279
27   Andrew Wiggins   0.475  0.516393    0.414  0.585579
30    Anthony Davis   0.506  0.535354    0.270  0.550536
31  Anthony Edwards   0.489  0.553696    0.399  0.617236
37    Austin Reaves   0.490  0.587558    0.360  0.641455
39      Bam Adebayo   0.442  0.508725    0.318  0.551415

In [37]:
two_point_pct_correlation = scorers_df["FG2_PCT"].corr(
    scorers_df["TS_PCT"]
)

two_point_pct_correlation

np.float64(0.7659917055497218)

In [38]:
correlation_columns = [
    "TS_PCT",
    "PTS_PER_GAME",
    "FG_PCT",
    "FG2_PCT",
    "FG3_PCT",
    "FT_PCT",
    "THREE_POINT_ATTEMPT_RATE",
    "FREE_THROW_RATE"
]

correlation_matrix = scorers_df[correlation_columns].corr()

correlation_matrix

                            TS_PCT  ...  FREE_THROW_RATE
TS_PCT                    1.000000  ...         0.553814
PTS_PER_GAME              0.373859  ...         0.362944
FG_PCT                    0.727802  ...         0.498577
FG2_PCT                   0.765992  ...         0.376432
FG3_PCT                  -0.035972  ...        -0.350802
FT_PCT                    0.098283  ...        -0.164284
THREE_POINT_ATTEMPT_RATE -0.207183  ...        -0.529115
FREE_THROW_RATE           0.553814  ...         1.000000

[8 rows x 8 columns]

In [39]:
fig = px.imshow(
    correlation_matrix,
    text_auto=".2f",
    aspect="auto",
    title="Correlation Matric of Scoring Metrics"
)

fig.show()

In [40]:
fig = px.scatter(
    scorers_df,
    x="FG2_PCT",
    y="TS_PCT",
    hover_name="PLAYER_NAME",
    title="Two-Point Percentage vs. True Shooting Percentage",
    trendline="ols"
)

fig.show()

In [41]:
fig = px.scatter(
    scorers_df,
    x="FREE_THROW_RATE",
    y="TS_PCT",
    hover_name="PLAYER_NAME",
    title="Free-Throw Rate vs. True Shooting Percentage",
    trendline="ols"
)

fig.show()

In [42]:
import statsmodels.api as sm

In [43]:
X = scorers_df[
    [
        "FG2_PCT",
        "FG3_PCT",
        "FT_PCT",
        "THREE_POINT_ATTEMPT_RATE",
        "FREE_THROW_RATE",
        "PTS_PER_GAME"
    ]
]

y = scorers_df["TS_PCT"]

In [44]:
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 TS_PCT   R-squared:                       0.853
Model:                            OLS   Adj. R-squared:                  0.843
Method:                 Least Squares   F-statistic:                     85.19
Date:                Fri, 28 Aug 2026   Prob (F-statistic):           1.68e-34
Time:                        14:45:29   Log-Likelihood:                 276.61
No. Observations:                  95   AIC:                            -539.2
Df Residuals:                      88   BIC:                            -521.3
Df Model:                           6
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -0.0151      0.033     -0.453      0.652      -0.081       0.051
FG2_PCT                      0.6960      0.041     17.081      0.000       0.615       0.777
FG3_PCT                      0.1191      0.033      3.635      0.000       0.054       0.184
FT_PCT                       0.1839      0.027      6.765      0.000       0.130       0.238
THREE_POINT_ATTEMPT_RATE     0.0051      0.016      0.323      0.748      -0.026       0.036
FREE_THROW_RATE              0.1241      0.016      7.524      0.000       0.091       0.157
PTS_PER_GAME                -0.0003      0.000     -0.666      0.507      -0.001       0.001
==============================================================================
Omnibus:                       23.193   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.294
Skew:                           1.095   Prob(JB):                     3.57e-08
Kurtosis:                       4.966   Cond. No.                         777.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [45]:
import pandas as pd

In [46]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()

vif_data["Variable"] = X.columns

vif_data["VIF"] = [
    variance_inflation_factor(X.values, i)
    for i in range(X.shape[1])
]

vif_data

                   Variable       VIF
0                     const  1.000000
1                   FG2_PCT  1.349463
2                   FG3_PCT  2.010913
3                    FT_PCT  1.547377
4  THREE_POINT_ATTEMPT_RATE  2.473195
5           FREE_THROW_RATE  1.710178
6              PTS_PER_GAME  1.467632